{% set name = "pdbpp" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 73ff220d5006e0ecdc3e2705d8328d8aa5ac27fef95cc06f6e42cd7d22d55eb8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
  run:
    - python
    - fancycompleter >=0.8
    - pygments
    - six
    - wmctrl
    # Optional, but with no version constraints
    # - funcsigs

test:
  requires:
    - pytest
    - funcsigs
  source_files:
    - testing
  # pdbpp replaces built-in pdb module and makes it available as pdb.pdb
  # if pdbpp was properly dropped in as pdb replacement the following import should work
  # on the other hand the built-in pdb does not have pdb.pdb 
  commands:
    - python -c "from pdb import pdb"
    - pytest testing


about:
  home: http://github.com/pdbpp/pdbpp
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'pdb++, a drop-in replacement for pdb'

  description: |
      This module is an extension of the pdb module of the standard library.
      It is meant to be fully compatible with its predecessor, yet it introduces
      a number of new features to make your debugging experience as nice as possible.
  dev_url: http://github.com/pdbpp/pdbpp

extra:
  recipe-maintainers:
    - sodre
    - kynan
    - megies
