{% set name = "pdbpp" %}
{% set version = "0.10.0" %}
{% set sha256 = "ee7eab02ecf32d92bd66b45eedb9bda152fa13f7be0dceb7050413a52cbbc4dd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .


requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
  run:
    - python
    - fancycompleter
    - wmctrl
    - pygments

test:
  # pdbpp replaces built-in pdb module and makes it available as pdb.pdb
  # if pdbpp was properly dropped in as pdb replacement the following import should work
  # on the other hand the built-in pdb does not have pdb.pdb
  commands:
    - python -c "from pdb import pdb"

about:
  home: http://github.com/antocuni/pdb
  license: BSD 3-Clause
  license_family: BSD
  summary: 'pdb++, a drop-in replacement for pdb'

  description: |
      This module is an extension of the pdb module of the standard library.
      It is meant to be fully compatible with its predecessor, yet it introduces
      a number of new features to make your debugging experience as nice as possible.
  dev_url: http://github.com/antocuni/pdb

extra:
  recipe-maintainers:
    - sodre
    - kynan
    - megies
