{% set name = "pdbpp" %}
{% set version = "0.11.7" %}
{% set sha256 = "cb6604ac31a35ed0f2a29650a8c022b26284620be3e01cfd41b683b91da1ff14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - fancycompleter >=0.11.0
    - wmctrl
    - pygments

test:
  # pdbpp replaces built-in pdb module and makes it available as pdb.pdb
  # if pdbpp was properly dropped in as pdb replacement the following import should work
  # on the other hand the built-in pdb does not have pdb.pdb 
  requires:
    - python {{ python_min }}
  commands:
    - python -c "from pdb import pdb"

about:
  home: https://pypi.org/project/pdbpp/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: pdb++, a drop-in replacement for pdb

  description: |
    This module is an extension of the pdb module of the standard library.
    It is meant to be fully compatible with its predecessor, yet it introduces
    a number of new features to make your debugging experience as nice as possible.
  dev_url: https://github.com/bretello/pdbpp

extra:
  recipe-maintainers:
    - sodre
    - kynan
    - megies
